# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{ULL-ESIT-LPP-2122/granja-alu0101128894}" }

gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"
